// frontend/components/Navbar.jsx
import Avatar from "./Avatar";
import LoginButton from "./LoginButton";
import ThemeSwitch from "./ThemeSwitch";
import { Logo } from "./Logo";
import { useAuth } from "../contexts/AuthContext";

const Navbar = () => {
  const { isAuthenticated, profile } = useAuth();

  return (
    <section className="grid place-items-end">
      <div className="navbar bg-base-100">
        <div className="navbar-start">
          <Logo />
        </div>
        <div className="navbar-center"></div>
        <div className="navbar-end">
          <ThemeSwitch />
          {isAuthenticated && profile ? <Avatar /> : <LoginButton />}
        </div>
      </div>
    </section>
  );
};

export default Navbar;

// frontend/src/components/Navbar.vue
<template>
  <section class="grid place-items-end">
    <div class="navbar bg-base-100">
      <div class="navbar-start">
        <Logo />
      </div>
      <div class="navbar-center"></div>
      <div class="navbar-end">
        <ThemeSwitch />
        <Avatar v-if="isAuthenticated" :profile="profile" />
        <button v-else class="btn gap-2 h-8 px-4 m-2 text-sm" @click="redirectToLogin">
          Login
        </button>
      </div>
    </div>
  </section>
</template>

<script>
import Avatar from "./Avatar.vue";
import Logo from "./Logo.vue";
import ThemeSwitch from "./ThemeSwitch.vue";
import { mapGetters } from "vuex";

export default {
  components: {
    Logo,
    ThemeSwitch,
    Avatar,
  },
  computed: {
    ...mapGetters(["isAuthenticated", "profile"]),
  },
  methods: {
    redirectToLogin() {
      this.$router.push("/login");
    },
  },
};
</script>
