// frontend/components/ProfileCard.jsx
import Image from "next/image";
import { capitalizeFirstLetter } from "../helpers/capitalize-first-letter";
import { splitByComma } from "../helpers/split-by-comma";

const ProfileCard = ({ profile }) => {
  const [city, country] = splitByComma(profile?.location);

  return (
    <>
      <div className="card card-compact w-auto max-w-[26rem] mt-8 bg-base-100 shadow-xl mx-3">
        <figure>
          <Image src={profile?.avatar} alt="Shoes" width="400" height="400" />
        </figure>
        <div className="card-body">
          <h2 className="card-title">
            {profile?.name}
            <span className="text-primary">{profile?.age}</span>
          </h2>

          <section className="space-x-2 space-y-2">
            <div className="badge badge-md gap-2">
              Breed <span className="font-extrabold">{profile?.breed}</span>
            </div>

            <div className="badge badge-md gap-2">
              Gender
              <span className="font-extrabold">{capitalizeFirstLetter(profile?.gender)}</span>
            </div>

            <div className="badge badge-md gap-2">
              <span className="font-extrabold">{city}</span>
              {country}
            </div>
          </section>
        </div>
      </div>
    </>
  );
};

export default ProfileCard;

// frontend/src/components/ProfileCard.vue
<template>
  <div class="card card-compact w-auto max-w-[26rem] mt-8 bg-base-100 shadow-xl mx-3">
    <figure>
      <img
        :src="profile?.avatar"
        class="w-full h-full min-h-[20rem] max-h-[20rem] object-cover"
        alt="profile-picture"
      />
    </figure>
    <div class="card-body">
      <h2 class="card-title">
        {{ capitalize(profile.name) }}
        <span class="ml-2 text-primary">{{ profile.age }}</span>
      </h2>

      <section class="space-x-2 space-y-2">
        <div class="badge badge-md gap-2">
          Breed <span class="font-extrabold">{{ profile.breed }}</span>
        </div>

        <div class="badge badge-md gap-2">
          Gender
          <span class="font-extrabold">{{ capitalize(profile.gender) }}</span>
        </div>

        <div class="badge badge-md gap-2">
          <span class="font-extrabold">{{ location[0] }}</span>
          {{ location[1] }}
        </div>
      </section>
    </div>
  </div>
</template>
<script>
import { capitalizeFirstLetter } from "../helpers/capitalize-first-letter";
import { splitByComma } from "../helpers/split-by-comma";

export default {
  props: {
    profile: {
      type: Object,
      required: true,
      default: () => ({
        avatar: null,
      }),
    },
  },
  computed: {
    location() {
      return splitByComma(this.profile.location);
    },
  },
  methods: {
    capitalize(value) {
      return capitalizeFirstLetter(value);
    },
  },
};
</script>
