// frontend/src/views/Matches.vue
<template>
  <Loading v-if="isLoading" />
  <ErrorAlert v-if="errorMessage" :error-message="errorMessage" />
  <div v-else class="grid place-items-center">
    <div class="card w-96 max-w-sm mt-8 bg-base-100">
      <div class="text-left">
        <div class="text-lg font-extrabold px-4">
          Reactions
          <div class="badge badge-primary mx-2">{{ reactionsAmount }}</div>
        </div>
      </div>

      <ReactionsCarousel :reactions="reactions" />

      <div class="text-left">
        <div class="text-lg font-extrabold px-4">
          Matches
          <div class="badge badge-secondary mx-2">{{ matchesAmount }}</div>
        </div>
      </div>

      <MatchRow v-for="(match, index) in matches" :key="index" :match="match" />
    </div>
  </div>
</template>
<script>
import ErrorAlert from "../components/ErrorAlert.vue";
import Loading from "../components/Loading.vue";
import MatchRow from "../components/MatchRow.vue";
import ReactionsCarousel from "../components/ReactionsCarousel.vue";
import { getMatches, getReactions } from "../services";
import { mapMutations } from "vuex";

export default {
  components: {
    Loading,
    ReactionsCarousel,
    MatchRow,
    ErrorAlert,
  },
  data() {
    return {
      isLoading: false,
      errorMessage: null,
      matches: [],
      reactions: [],
    };
  },
  computed: {
    matchesAmount() {
      return this.matches.length;
    },
    reactionsAmount() {
      return this.reactions.length;
    },
  },
  async mounted() {
    this.isLoading = true;

    await this.fetchReactions();
    await this.fetchMatches();

    this.isLoading = false;
  },
  methods: {
    ...mapMutations(["setMatchesAmount"]),
    async fetchReactions() {
      try {
        const { reactions, error } = await getReactions();

        if (!error) {
          this.reactions = reactions ?? [];
        }

        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      } catch (error) {
        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      }
    },
    async fetchMatches() {
      try {
        const { matches, error } = await getMatches();

        if (!error) {
          this.matches = matches ?? [];
          this.setMatchesAmount(matches.length);
        }

        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      } catch (error) {
        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      }
    },
    resetErrorMessage() {
      setTimeout(() => {
        this.errorMessage = null;
      }, 3000);
    },
  },
};
</script>

// frontend/pages/matches.jsx
import { MatchRow } from "../components/MatchRow";
import { ReactionsCarousel } from "../components/ReactionsCarousel";
import { getReactions } from "../utils/api/get-reactions";
import { useAuth } from "../contexts/AuthContext";
import { useEffect, useState } from "react";

const Matches = () => {
  const { accessToken, setError } = useAuth();
  const [reactions, setReactions] = useState();

  const matches = [];

  useEffect(() => {
    (async () => {
      if (!reactions) {
        const { reactions: fetchedReactions, error: fetchError } = await getReactions(accessToken);

        if (fetchError) {
          setError(fetchError);
          setTimeout(() => {
            setError();
          }, 3000);
        }

        setReactions(fetchedReactions ?? []);
      }
    })();
  }, []);

  return (
    <div className="grid place-items-center">
      <div className="card w-auto mt-8 bg-base-100 mx-3">
        <div className="text-left ">
          <div className="text-lg font-extrabold px-4">
            Reactions
            <div className="badge badge-primary mx-2">{reactions?.length}</div>
          </div>
        </div>

        <ReactionsCarousel reactions={reactions} />

        <div className="text-left ">
          <div className="text-lg font-extrabold px-4">
            Matches
            <div className="badge badge-secondary mx-2">{matches.length}</div>
          </div>
        </div>

        {matches.map((match, index) => (
          <MatchRow key={index} match={match} />
        ))}
      </div>
    </div>
  );
};

export default Matches;
