// frontend/src/views/Profile.vue
<template>
  <Loading v-if="isLoading" />
  <ErrorAlert v-if="errorMessage" :error-message="errorMessage" />
  <div class="card w-auto mt-8 bg-base-100 shadow-xl mx-3">
    <section v-if="!isEditing" class="grid place-items-end p-4">
      <button class="btn btn-sm" @click="setEditingProfile(true)">Edit</button>
    </section>

    <section class="grid place-items-center mt-6">
      <div class="avatar">
        <div class="w-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
          <img v-if="profile?.avatar" :src="profile?.avatar?.url" alt="avatar" />
          <img v-else src="../assets/default-avatar.svg" alt="avatar" />
        </div>
      </div>
    </section>

    <section class="grid p-4">
      <ValidatedForm
        v-if="isEditing"
        v-slot="{ errors, values }"
        :validation-schema="updateProfileValidationSchema"
      >
        <section class="grid place-items-center">
          <Field
            name="name"
            type="text"
            placeholder="Name"
            class="input input-bordered w-full mt-10"
            :class="{ 'input-primary': !errors.name, 'input-error': errors.name }"
            :value="profile.name"
          />
          <label class="label">
            <ErrorMessage as="span" name="name" class="label-text-alt text-error" />
          </label>

          <Field
            name="breed"
            as="select"
            class="select w-full mt-6"
            :class="{ 'input-primary': !errors.breed, 'input-error': errors.breed }"
            :value="profile?.breed"
          >
            <option :value="profile?.breed">{{ profile?.breed }}</option>
            <option v-for="(breed, index) in breeds" :key="index" :value="breed">
              {{ breed }}
            </option>
          </Field>
          <label class="label">
            <ErrorMessage as="span" name="breed" class="label-text-alt text-error" />
          </label>

          <Field
            name="gender"
            as="select"
            class="select w-full mt-6"
            :class="{ 'input-primary': !errors.gender, 'input-error': errors.gender }"
            :value="profile.gender"
          >
            <option :value="profile.gender">{{ capitalize(profile.gender) }}</option>
            <option v-if="profile.gender === 'female'" value="male">Male</option>
            <option v-else value="female">Female</option>
          </Field>
          <label class="label">
            <ErrorMessage as="span" name="gender" class="label-text-alt text-error" />
          </label>

          <Field
            name="location"
            type="text"
            placeholder="City, Country"
            class="input input-bordered w-full mt-6"
            :class="{ 'input-primary': !errors.location, 'input-error': errors.location }"
            :value="profile.location"
          />
          <label class="label">
            <ErrorMessage as="span" name="location" class="label-text-alt text-error" />
          </label>
        </section>
        <section class="flex justify-end">
          <button
            class="btn btn-sm btn-link text-neutral mt-8 mr-2"
            @click="setEditingProfile(false)"
          >
            Cancel
          </button>
          <button class="btn btn-sm mt-8" @click="handleProfileUpdate(values)">Save</button>
        </section>
      </ValidatedForm>

      <section v-else>
        <div class="text-left">
          <div class="text-xl font-extrabold">
            {{ capitalize(profile.name) }}
            <span class="ml-2 text-primary">{{ profile.age }}</span>
          </div>

          <section class="space-x-2">
            <div class="badge badge-lg mt-4 gap-2">
              Breed <span class="font-extrabold">{{ profile.breed }}</span>
            </div>

            <div class="badge badge-lg mt-4 gap-2">
              Gender
              <span class="font-extrabold">{{ capitalize(profile.gender) }}</span>
            </div>

            <div class="badge badge-lg mt-4 gap-2">
              <span class="font-extrabold">{{ location[0] }}</span>
              {{ location[1] }}
            </div>
          </section>
        </div>
      </section>
    </section>
  </div>
</template>
<script>
import ErrorAlert from "../components/ErrorAlert.vue";
import Loading from "../components/Loading.vue";
import { ErrorMessage, Field, Form } from "vee-validate";
import { capitalizeFirstLetter } from "../helpers/capitalize-first-letter";
import { getBreeds, updateProfile } from "../services";
import { mapGetters, mapMutations } from "vuex";
import { splitByComma } from "../helpers/split-by-comma";
import { updateProfileValidationSchema } from "../validators/profile.validator";

export default {
  components: {
    ValidatedForm: Form,
    Field,
    ErrorMessage,
    Loading,
    ErrorAlert,
  },
  data() {
    return {
      isLoading: false,
      isEditing: false,
      breeds: [],
      errorMessage: null,
      updateProfileValidationSchema,
    };
  },
  computed: {
    ...mapGetters(["profile"]),
    location() {
      return splitByComma(this.profile.location);
    },
  },
  async mounted() {
    this.isLoading = true;

    await this.fetchBreeds();

    this.isLoading = false;
  },
  methods: {
    ...mapMutations(["setProfile"]),
    setEditingProfile(state) {
      this.isEditing = state;
    },
    capitalize(value) {
      return capitalizeFirstLetter(value);
    },
    async fetchBreeds() {
      try {
        const { breeds, error } = await getBreeds();

        if (!error) {
          this.breeds = breeds ?? [];
        }

        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      } catch (error) {
        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      }
    },
    async handleProfileUpdate(payload) {
      this.isLoading = true;

      try {
        const { profile, error } = await updateProfile(payload);

        if (!error) {
          this.isLoading = false;
          this.isEditing = false;
          this.setProfile(profile);
        }

        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      } catch (error) {
        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      }
    },
    resetErrorMessage() {
      setTimeout(() => {
        this.errorMessage = null;
      }, 3000);
    },
  },
};
</script>

// frontend/pages/profile.jsx
import * as yup from "yup";
import { capitalizeFirstLetter } from "../helpers/capitalize-first-letter";
import { getBreeds } from "../utils/api/get-breeds";
import { splitByComma } from "../helpers/split-by-comma";
import { updateProfile } from "../utils/api/update-profile";
import { useAuth } from "../contexts/AuthContext";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";

const Profile = () => {
  const { profile, accessToken, setError, setProfile } = useAuth();
  const [isEditing, setEditing] = useState(false);
  const [breedList, setBreedList] = useState();

  const [city, country] = splitByComma(profile.location);
  const today = new Date();

  useEffect(() => {
    (async () => {
      if (!breedList) {
        const { breeds, error } = await getBreeds(accessToken);

        if (error) {
          setError(error);
          setTimeout(() => {
            setError();
          }, 3000);
        }

        setBreedList(breeds ?? []);
      }
    })();
  }, [breedList]);

  const validationSchema = yup.object().shape({
    name: yup
      .string()
      .min(2, "Name must be at least 2 characters")
      .max(64, "Name must be 64 characters maximum")
      .required("Name is required"),
    breed: yup.string().required("Breed is required"),
    dateOfBirth: yup
      .date()
      .typeError("Must be valid date")
      .max(today, "Date cannot be in the future")
      .required("Date of birth is required"),
    gender: yup.mixed().oneOf(["female", "male"]),
    location: yup
      .string()
      .min(6, "Location must be at least 6 characters")
      .max(64, "Location must be 64 characters maximum")
      .required("Location is required"),
  });

  const formOptions = {
    resolver: yupResolver(validationSchema),
    defaultValues: useMemo(() => profile, [profile]),
  };
  const { register, handleSubmit, formState } = useForm(formOptions);
  const { errors } = formState;

  const onSubmit = async (data) => {
    const { profile, error: updateError } = await updateProfile(data);

    if (updateError) {
      setError(updateError);
      setTimeout(() => {
        setError();
      }, 3000);
    }

    setProfile(profile);
    setEditing(false);
  };

  return (
    <div className="card w-auto mt-8 bg-base-100 shadow-xl mx-3">
      {!isEditing && (
        <section className="grid place-items-end p-4">
          <button className="btn btn-sm" onClick={() => setEditing(true)}>
            Edit
          </button>
        </section>
      )}
      <section className="grid place-items-center mt-6">
        <div className="avatar">
          <div className="w-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
            <img src="/assets/images/akita.webp" />
          </div>
        </div>
      </section>
      <section className="grid p-4">
        {isEditing ? (
          <form onSubmit={handleSubmit(onSubmit)}>
            <section className="grid place-items-center">
              <input
                type="text"
                placeholder="Name"
                {...register("name")}
                className={`input input-bordered ${
                  errors.email ? "input-error" : "input-primary"
                } w-full max-w-xs mt-10`}
              />
              {errors.name?.message ? (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.name?.message}</span>
                </label>
              ) : null}

              <select
                className={`select  ${
                  errors.breed ? "select-error" : "select-primary"
                } w-full max-w-xs mt-6`}
                {...register("breed")}
              >
                <option disabled value="placeholder">
                  Choose breed
                </option>
                {breedList.map((breed, index) => (
                  <option key={index} value={breed}>
                    {breed}
                  </option>
                ))}
              </select>
              {errors.breed?.message ? (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.breed?.message}</span>
                </label>
              ) : null}

              <select
                className={`select  ${
                  errors.breed ? "select-error" : "select-primary"
                } w-full max-w-xs mt-6`}
                {...register("gender")}
              >
                <option disabled value="placeholder">
                  Choose gender
                </option>
                <option value="female">Female</option>
                <option value="male">Male</option>
              </select>
              {errors.gender?.message ? (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.gender?.message}</span>
                </label>
              ) : null}

              <input
                type="text"
                placeholder="City, Country"
                {...register("location")}
                className={`input input-bordered ${
                  errors.location ? "input-error" : "input-primary"
                } w-full max-w-xs mt-6`}
              />
              {errors.location?.message ? (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.location?.message}</span>
                </label>
              ) : null}
            </section>
            <section className="flex justify-end">
              <button
                className="btn btn-sm btn-link text-neutral mt-8 mr-2"
                onClick={() => setEditing(false)}
              >
                Cancel
              </button>
              <button type="submit" className="btn btn-sm mt-8">
                Save
              </button>
            </section>
          </form>
        ) : (
          <section className="p-8">
            <div className="text-left">
              <div className="text-xl font-extrabold">
                {capitalizeFirstLetter(profile.name)}
                <span className="ml-2 text-primary">{profile.age}</span>
              </div>

              <section className="space-x-2">
                <div className="badge badge-lg mt-4 gap-2">
                  Breed <span className="font-extrabold">{profile.breed}</span>
                </div>

                <div className="badge badge-lg mt-4 gap-2">
                  Gender
                  <span className="font-extrabold">{capitalizeFirstLetter(profile.gender)}</span>
                </div>

                <div className="badge badge-lg mt-4 gap-2">
                  <span className="font-extrabold">{city}</span>
                  {country}
                </div>
              </section>
            </div>
          </section>
        )}
      </section>
    </div>
  );
};

export default Profile;
