// frontend/pages/login.jsx
import ErrorAlert from "../components/ErrorAlert";
import Link from "next/link";
import * as yup from "yup";
import { useAuth } from "../contexts/AuthContext";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";

const Login = () => {
  const validationSchema = yup.object().shape({
    email: yup.string().required("Email is required").email("Email is invalid"),
    password: yup
      .string()
      .min(8, "Password must be at least 8 characters")
      .max(64, "Password must be 64 characters maximum")
      .required("Password is required"),
  });

  const formOptions = { resolver: yupResolver(validationSchema) };
  const { register, handleSubmit, formState } = useForm(formOptions);
  const { errors } = formState;

  const { login, error: loginError } = useAuth();

  const onSubmit = (data) => login(data);

  return (
    <>
      <form onSubmit={handleSubmit(onSubmit)}>
        <section className="grid place-items-center">
          <input
            type="text"
            placeholder="Email"
            {...register("email")}
            className={`input input-bordered ${
              errors.email ? "input-error" : "input-primary"
            } w-full max-w-xs mt-10`}
          />
          {errors.email?.message ? (
            <label className="label">
              <span className="label-text-alt text-error">{errors.email?.message}</span>
            </label>
          ) : null}
          <input
            type="password"
            placeholder="Password"
            {...register("password")}
            className={`input input-bordered ${
              errors.password ? "input-error" : "input-primary"
            } w-full max-w-xs mt-6`}
          />
          {errors.password?.message ? (
            <label className="label">
              <span className="label-text-alt text-error">{errors.password?.message}</span>
            </label>
          ) : null}
          <p className="mt-4 text-xs">
            No account yet?
            <Link href="/register">
              <a className="link link-hover ml-1">Register</a>
            </Link>
          </p>
          <button className="btn btn-primary btn-wide mt-4 w-80">Login</button>
        </section>
      </form>
      {loginError && (
        <ErrorAlert
          message={
            loginError.statusCode === 401 ? "Invalid email or password" : "Unknown error occurred"
          }
        />
      )}
    </>
  );
};

export default Login;

// frontend/src/views/Login.vue
<template>
  <ErrorAlert v-if="errorMessage" :error-message="errorMessage" />
  <ValidatedForm
    v-slot="{ errors }"
    :validation-schema="loginValidationSchema"
    @submit="handleLogin"
  >
    <Field
      name="email"
      type="text"
      placeholder="Email"
      class="input input-bordered w-full max-w-xs mt-10"
      :class="{ 'input-primary': !errors.email, 'input-error': errors.email }"
    />
    <label class="label">
      <ErrorMessage as="span" name="email" class="label-text-alt text-error" />
    </label>

    <Field
      name="password"
      type="password"
      placeholder="Password"
      class="input input-bordered w-full max-w-xs mt-4"
      :class="{ 'input-primary': !errors.password, 'input-error': errors.password }"
    />
    <label class="label">
      <ErrorMessage as="span" name="password" class="label-text-alt text-error" />
    </label>

    <p class="text-xs">
      No account yet?
      <a class="link link-hover ml-1" @click="redirectToRegister">Register</a>
    </p>

    <button class="btn btn-primary btn-wide mt-4 w-80">Login</button>
  </ValidatedForm>
</template>

<script>
import ErrorAlert from "../components/ErrorAlert.vue";
import { ErrorMessage, Field, Form } from "vee-validate";
import { loginValidationSchema } from "../validators/login.validator";
import { mapActions } from "vuex";

export default {
  components: {
    ValidatedForm: Form,
    Field,
    ErrorMessage,
    ErrorAlert,
  },
  data() {
    return {
      isLoading: false,
      errorMessage: null,
      loginValidationSchema,
    };
  },
  methods: {
    ...mapActions(["login"]),
    async handleLogin(payload) {
      this.isLoading = true;

      try {
        const { error } = await this.login(payload);

        this.isLoading = false;

        if (!error) {
          await this.$router.push("/");
        }

        this.errorMessage = error?.message;

        this.resetErrorMessage();
      } catch (error) {
        this.isLoading = false;
        this.errorMessage = error?.message;

        this.resetErrorMessage();
      }
    },
    resetErrorMessage() {
      setTimeout(() => {
        this.errorMessage = null;
      }, 3000);
    },
    redirectToRegister() {
      this.$router.push("/register");
    },
  },
};
</script>
